version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    labels:
      - 'area/dependencies'
      - 'bots'
      - 'kind/chore'
    schedule:
      interval: 'monthly'

  - package-ecosystem: 'github-actions'
    directory: '/'
    labels:
      - 'area/dependencies'
      - 'bots'
      - 'kind/chore'
    schedule:
      interval: 'monthly'
